# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import tickets.enums


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Low')], default=tickets.enums.Urgency('Low'), max_length=20),
        ),
    ]
