# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import tickets.enums


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default=tickets.enums.Urgency('Low'), max_length=20),
        ),
    ]
