# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180514_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
