# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
